# Generated by Django 6.1.1 on 2026-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('sinopsis', models.TextField(blank=True)),
                ('episodios', models.IntegerField(default=12)),
                ('visto', models.BooleanField(default=False)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'animes',
                'ordering': ['titulo'],
            },
        ),
    ]
